<?php
echo "<table align='left' width='30%' border='1' cellspacing='0'>";
echo "  <tr>";
echo "	  <th>Trabajador:</th>";
echo "    <th>Horario</th>";
echo "	  <th>Departamento</th>";
echo "  </tr>";
echo "  <tr>";
echo "    <td>María Luisa Rojas</td>";
echo "    <td>8 am a 3 pm</td>";
echo "    <td>Producción</td>";
echo "  </tr>";
echo "  <tr>";
echo "    <td>José Pérez Márquez</td>";
echo "    <td>3 pm a 10 pm</td>";
echo "    <td>Seguridad</td>";
echo "  </tr>";
echo "  <tr>";
echo "	  <td>Catalina Donoso Correa</td>";
echo "	  <td>10 pm a 6 am</td>";
echo "	  <td>Producción</td>";
echo "  </tr>";
echo "  <tr>";
echo "	  <td>Raúl Lavín</td>";
echo "    <td>8 am a 3 pm</td>";
echo "    <td>Producción</td>";
echo "  </tr>";
echo "  <tr>";
echo "	  <td>Jorge Luis Venegas</td>";
echo "	  <td>3 pm a 10 pm</td>";
echo "	  <td>Logística</td>";
echo "  </tr>";
echo "  <tr>";
echo "</table>";